services:

  jwt-demo-reverse-proxy:
    container_name: jwt-demo-reverse-proxy
    build:
      context: ../
      dockerfile: ./packages/jwt-demo-reverse-proxy/Dockerfile
    ports:
      - 9090:80
    networks:
      - intranet


  jwt-demo-api:
    container_name: jwt-demo-api
    build:
      context: ../
      dockerfile: ./packages/jwt-demo-api/Dockerfile
      args:
        - NODE_ENV
        - HTTP_PROXY
        - HTTPS_PROXY
        - ACCESS_TOKEN_SECRET
    networks:
      - intranet


  jwt-demo-auth:
    container_name: jwt-demo-auth
    build:
      context: ../
      dockerfile: ./packages/jwt-demo-auth/Dockerfile
      args:
        - NODE_ENV
        - HTTP_PROXY
        - HTTPS_PROXY
        - ACCESS_TOKEN_SECRET
        - REFRESH_TOKEN_SECRET
    networks:
      - intranet


  jwt-demo-frontend:
    container_name: jwt-demo-frontend
    build:
      context: ../
      dockerfile: ./packages/jwt-demo-frontend/Dockerfile
    networks:
      - intranet


  jwt-demo-redis:
    image: redis:6.0.10-alpine
    container_name: jwt-demo-redis
    networks:
      - intranet

networks:
  intranet:
